name:                text-transforms
version:             0.1.0.0
github:              "githubuser/text-transforms"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/text-transforms#readme>

dependencies:
- base
- text
- taggy
- taggy-lens
- tagchup
- lens
- mtl
- turtle
- hscolour
- pretty-show
- pretty-simple
- lucid
- parsec
- foldl
- vector
- containers
- split
- tagsoup

library:
  source-dirs: src

tests:
  text-transforms-test:
    main: Driver.hs
    source-dirs: tests
    dependencies:
    - base
    - tasty
    - tasty-hunit
    - tasty-hspec
    - text-transforms
    build-tools:
      - tasty-discover

executables:
  lingvist-to-anki:
    main:                Main.hs
    source-dirs:         lingvist-to-anki
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-transforms

  wikipedia-latex:
    main:                Main.hs
    source-dirs:         wikipedia-latex
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-transforms

  mathpix-list-format:
    main:                Main.hs
    source-dirs:         mathpix-list-format
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-transforms
    - lucid
    - attoparsec
    - foldl

  markdown-to-html:
    main:                Main.hs
    source-dirs:         markdown-to-html
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-transforms
    - lucid
    - parsec
    - foldl

  unindent-headers-bullets:
    main:                Main.hs
    source-dirs:         unindent-headers-bullets
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-transforms
    - parsec
    - foldl
