name:                wikipedia-latex
version:             0.1.0.0
github:              "githubuser/wikipedia-latex"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wikipedia-latex#readme>

dependencies:
- base >= 4.7 && < 5
- text
- taggy
- taggy-lens
- tagchup
- lens
- mtl
- turtle
- hscolour
- pretty-show

library:
  source-dirs: src

executables:
  wikipedia-latex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wikipedia-latex
